# Generated by Django 4.0.6 on 2022-07-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
